### ISSUE TITLE
Include empty folders

### ISSUE THREAD

**Issue by vernjan** [paleozogt/symzip-plugin#1]
Empty folders are excluded from the archive. This causes issues if the project relies on presence of empty folders.

**Comment by paleozogt** [comment]
Good find!  I've fixed this and released 0.9.4.  (It might take a few hours to propagate to maven central.)

**Comment by paleozogt** [comment]
@vernjan looks like maven central has picked up 0.9.4.  Can you try it out and let me know if it fixes your issue?

**Comment by vernjan** [comment]
Hi, works for me.
Thanks!
